ccs-calendarserver: Address build issues with newer dependencies
* Update to openssl 1.0.2r in ./bin/_build.sh
* Update to sqlparse 0.2.4 in ./requirements-cs.txt
* **WARNING**: Does not yet address `invoke './Configure darwin64-x86_64-cc' *manually*` in `.develop/src/openssl-1.0.2r/config`, `ld: symbol(s) not found for architecture i386` errors
* See: https://github.com/apple/ccs-twistedextensions/pull/20
* See: https://gist.github.com/essandess/4c9b5d906896ff4aef6170fc18f2c293

Comments:
* OpenSSL build issues may be sidestepped by using the MacPorts (or other) openssl installs as system libraries. This is preferred to using a package-specific library that may not be upgraded as regularly as its dependency. Working example that yields a successful run of `./bin/package /path/to/CalendarServer`:
```
cat <<PACKAGE_CALENDARSERVER | sh -x
(
    export PATH=/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
    export C_INCLUDE_PATH=/opt/local/include:/usr/include:/usr/local/include
    export LD_LIBRARY_PATH=/opt/local/lib:/opt/local/lib/openssl-1.0:/usr/lib:/usr/local/lib
    export CPPFLAGS='-I/opt/local/include -I/usr/include -I/usr/local/include'
    export LDFLAGS='-L/opt/local/lib -L/opt/local/lib/openssl-1.0 -L/usr/lib -L/usr/local/lib'
    export DYLD_LIBRARY_PATH=/opt/local/lib:/opt/local/lib/openssl-1.0:/usr/lib:/usr/local/lib

    ./bin/package -F /private/var/calendarserver/Library/CalendarServer 1> ~/ccs-calendarserver.log 2>&1
)
PACKAGE_CALENDARSERVER
```